### PR TITLE
Fix the Broken `malloc_n` Behavior

### LINKED ISSUE #52: `malloc_n` method inconsistency from `boost::simple_segregated_storage`?
Hello Boost Pool developers,

I was making some attempts to use `boost::simple_segregated_storage` by modifying the [example](https://theboostcpplibraries.com/boost.pool#ex.pool_01).

This example worked.

```c++
#include <boost/pool/simple_segregated_storage.hpp>
#include <cstddef>
#include <vector>
#include <cassert>
#include <iostream>
#include <stdexcept>

int main()
{
    boost::simple_segregated_storage<std::size_t> storage;
    std::vector<char> v1(5120);
    storage.add_ordered_block(&v1.front(), v1.size(), 256);
    int* j = static_cast<int*>(storage.malloc_n(1, 1024));
    if (j == nullptr)
    {
        throw std::runtime_error{"Contiguous memory trunks not found."};
    }
    storage.ordered_free_n(j, 1, 1024);
}
```

But this example did not work.

```c++
#include <boost/pool/simple_segregated_storage.hpp>
#include <cstddef>
#include <vector>
#include <cassert>
#include <iostream>
#include <stdexcept>

int main()
{
    boost::simple_segregated_storage<std::size_t> storage;
    std::vector<char> v1(5120);
    storage.add_ordered_block(&v1.front(), v1.size(), 256);
    int* j = static_cast<int*>(storage.malloc_n(2, 1024));
    if (j == nullptr)
    {
        throw std::runtime_error{"Contiguous memory trunks not found."};
    }
    storage.ordered_free_n(j, 2, 1024);
}
```

If my understanding of `boost::simple_segregated_storage` from [here](https://www.boost.org/doc/libs/1_80_0/libs/pool/doc/html/boost_pool/pool/pooling.html#boost_pool.pool.pooling.concepts) is correct, the `boost::simple_segregated_storage` design should either allow or deny both of the examples above (I personally favor denying both of the examples), but not just one worked and the other one did not.

Can you provide some clarifications about the `malloc_n` method here? Thank you.

### PR DESCRIPTION
**Pull request by leimao**
Fix #52 and added unit tests.

### CODE REVIEW

**Comment by leimao** [comment]
@mclow Could you please approve me running the test workflow to see if it will pass the existing unit tests?

**Comment by leimao** [comment]
Also tagging @jzmaddock for enabling first-time user workflow.

**Comment by leimao** [comment]
The patch works. Can someone please review and approve? Thank you.

**Comment by jzmaddock** [comment]
I've approved the run, but I'm not sure how up to date the CI scripts are.  We've also often talked about marking this library deprecated, but that appears not to have happened yet :(

**Comment by leimao** [comment]
> I've approved the run, but I'm not sure how up to date the CI scripts are. We've also often talked about marking this library deprecated, but that appears not to have happened yet :(

@jzmaddock Do you still suggest merging this patch? There is a small coverage check failing which I shall further investigate.

**Comment by jzmaddock** [comment]
>Do you still suggest merging this patch? There is a small coverage check failing which I shall further investigate.

I know it's a relatively trivial patch, but I still need to find the time to do a proper eyeball-checkover before merging.  Please nag me if I don't get to it soon-ish.

**Comment by leimao** [comment]
Thanks @jzmaddock. Take your time. Some of the new unit tests I added this morning trying to remedy the unit test coverage issues yesterday seems having some problems. I will check and try fixing them later today or tomorrow.

**Comment by leimao** [comment]
@jzmaddock I tested the new patch I just uploaded locally and it worked. Hope this time the test coverage issue can be fixed.

**Comment by leimao** [comment]
@jzmaddock Request running more test workflows.

**Comment by leimao** [comment]
@jzmaddock With the new unit test, it added one additional coverage comparing to the previous commit [[cf9b5c4](https://github.com/boostorg/pool/pull/53/commits/cf9b5c4a820e4221cbcf50d652b53742777de1e9)](https://github.com/boostorg/pool/pull/53/commits/cf9b5c4a820e4221cbcf50d652b53742777de1e9). But it's still missing one coverage comparing to the develop branch. Is it something that has to be fixed in order to get the pull request merged? Thanks.

**Comment by leimao** [comment]
@jzmaddock Added one more unit test. I ran some local unit test to see if the logic will flow to the positions where the coverage test failed. It seems that it will help. Please run the test workflow again. Thanks.

**Comment by leimao** [comment]
@jzmaddock

**Comment by leimao** [comment]
@jzmaddock It seems that it has passed all the checks. Could you please review and merge if possible?

**Comment by leimao** [comment]
@jzmaddock Bothering you again :)

**Comment by leimao** [comment]
@jzmaddock @pabristow Can some of you please review?

**Comment by leimao** [comment]
@jzmaddock

**Comment by leimao** [comment]
@jzmaddock @mclow

**Comment by jzmaddock** [comment]
This all checks out, thanks for persevering!

**Comment by leimao** [comment]
> This all checks out, thanks for persevering!

Thank you very much!

**Pull request merged**
