### PR TITLE
improve guards around boost/thread/mutex.hpp

### PR DESCRIPTION
**Pull request by nschloe**
Fixes bug #7085 (https://svn.boost.org/trac/boost/ticket/7085).

### CODE REVIEW

**Comment by mclow** [comment]
So, the goal here is if you define `BOOST_POOL_NO_MT`, then you don't include "mutex.hpp"?

**Comment by nschloe** [comment]
Indeed. The discussion at https://svn.boost.org/trac/boost/ticket/7085 gives more details.

**Comment by mclow** [comment]
Looks good to me. Please watch the test bots and ping me in a few days to merge to master (after the 1.59.0 release is done).

**Comment by nschloe** [comment]
Um, wait. Am I supposed to watch the test bots? Okay. Where can I do that?

**Comment by mclow** [comment]
Here: http://www.boost.org/development/tests/develop/developer/pool.html

**Comment by nschloe** [comment]
> ping me in a few days to merge to master

@mclow Ping!

**Comment by nschloe** [comment]
@mclow Has this been merged to master yet?

**Comment by mclow** [comment]
Just did.

**Comment by nschloe** [comment]
Perfect, thanks!

**Pull request merged**
